### ISSUE TITLE
An error occurred at callback_add_to_messages: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by paulirish** [mxngls/Gmail-Cleaner#1]
tried this out but ran into a few errors pretty quick. i did option 1 (most common senders).

as the progress bar was going.. i got this message flooding in:

> An error occurred at callback_add_to_messages: 'NoneType' object is not subscriptable

and then when it was done:

```
An error occurred at callback_add_to_messages: 'NoneType' object is not subscriptable
An error occurred at callback_add_to_messages: 'NoneType' object is not subscriptable
100%|██████████████████████████████████████████████████████████| 242/242 [02:18<00:00,  1.75it/s]
How much senders do you want to get displayed?
10
You have:
- 680 e-mails from xxxxxx@gmail.com.
- 494 e-mails from events@communications.okaything.com.
Traceback (most recent call last):
  File "/Users/paul/x/Gmail-Cleaner/src/gmailCleaner.py", line 144, in <module>
    main()
  File "/Users/paul/x/Gmail-Cleaner/src/gmailCleaner.py", line 44, in main
    match = re.search("(?<=<)(.*)(?=>)" , gmail.users[i][0]).group()
AttributeError: 'NoneType' object has no attribute 'group'
```

and it exited non-zero right after.

Not a huge deal to me, but.. figured you'd want the report. Cheers.

**Comment by mxngls** [comment]
Hi Paul,

thanks for the report. I mean to fix this script for a couple of months now, but somehow I never got to do it yet.

The script as it is right now is not quite robust - as you had to experience yourself. I never encountered the error you reported myself yet though (though this doesn't mean much). 

I'll probably tackle a rewrite sometime around June.

**Comment by mxngls** [comment]
@paulirish In the end it took me a year to come back and fix the script, but it should work again. I tested it on my own inbox and everything works well enough.
